# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-04 03:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='部门')),
            ],
        ),
        migrations.CreateModel(
            name='Deploy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=32, verbose_name='版本')),
                ('uid', models.CharField(blank=True, max_length=32, null=True, verbose_name='上线文件包名称')),
                ('status', models.IntegerField(choices=[(1, '未获取'), (2, '待发布'), (3, '已发布'), (4, '已回滚')], default=1, verbose_name='状态')),
            ],
        ),
        migrations.CreateModel(
            name='DeployRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_version', models.CharField(max_length=32, null=True, verbose_name='版本')),
                ('status', models.IntegerField(choices=[(1, '发布中'), (2, '成功'), (3, '失败')], default=1, verbose_name='状态')),
                ('deploy_time', models.DateTimeField(auto_now_add=True, verbose_name='部署时间')),
                ('log', models.TextField(verbose_name='日志')),
                ('deploy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Deploy', verbose_name='部署任务')),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=32, verbose_name='主机名')),
                ('ssh_port', models.IntegerField(verbose_name='SSH端口')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='项目名称')),
                ('git', models.CharField(max_length=128, verbose_name='仓库地址')),
                ('private', models.BooleanField(default=True, verbose_name='是否私有')),
                ('online_path', models.CharField(max_length=128, verbose_name='线上项目路径')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Department', verbose_name='部门')),
                ('hosts', models.ManyToManyField(to='web.Host', verbose_name='关联主机')),
            ],
        ),
        migrations.CreateModel(
            name='RollbackRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_version', models.CharField(max_length=32, null=True, verbose_name='版本')),
                ('status', models.IntegerField(choices=[(1, '发布中'), (2, '成功'), (3, '失败')], default=1, verbose_name='状态')),
                ('deploy_time', models.DateTimeField(auto_now_add=True, verbose_name='部署时间')),
                ('rollback_log', models.TextField(verbose_name='日志')),
                ('deploy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Deploy', verbose_name='部署任务')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Host', verbose_name='主机')),
            ],
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('interpreter', models.CharField(choices=[('py', 'python3'), ('sh', 'bash')], default='py', max_length=16, verbose_name='解释器')),
                ('code', models.TextField(verbose_name='上传脚本')),
                ('rollback_code', models.TextField(null=True, verbose_name='回滚脚本')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('server_name', models.CharField(max_length=32, verbose_name='SSH用户名')),
                ('server_private_key', models.TextField(verbose_name='SSH私钥')),
                ('git_name', models.CharField(max_length=32, verbose_name='git用户名')),
                ('git_pwd', models.CharField(max_length=32, verbose_name='git密码')),
            ],
        ),
        migrations.AddField(
            model_name='deployrecord',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Host', verbose_name='主机'),
        ),
        migrations.AddField(
            model_name='deploy',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Project', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='deploy',
            name='script',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Script', verbose_name='script'),
        ),
    ]
