# Generated by Django 2.2.1 on 2019-06-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployrecord',
            name='other',
        ),
        migrations.AddField(
            model_name='host',
            name='other',
            field=models.CharField(blank=True, max_length=32, verbose_name='备注'),
        ),
    ]
