# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-11 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploy',
            name='branch',
            field=models.CharField(max_length=32, null=True, verbose_name='分支'),
        ),
    ]
