# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-14 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_deploy_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deploy',
            name='version',
        ),
        migrations.AddField(
            model_name='deploy',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='拉取时间'),
        ),
        migrations.AlterField(
            model_name='deployrecord',
            name='deploy_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='script',
            name='interpreter',
            field=models.CharField(choices=[('sh', 'bash'), ('py', 'python3')], default='py', max_length=16, verbose_name='解释器'),
        ),
    ]
