# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-18 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20190114_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='文件名称')),
                ('filename', models.TextField(verbose_name='填写文件名称')),
            ],
        ),
        migrations.AlterField(
            model_name='deploy',
            name='status',
            field=models.IntegerField(choices=[(1, '未获取'), (2, '待发布'), (3, '已发布')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='deployrecord',
            name='status',
            field=models.IntegerField(choices=[(1, '发布中'), (2, '发布成功'), (3, '发布失败')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='rollbackrecord',
            name='deploy_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='回滚时间'),
        ),
        migrations.AlterField(
            model_name='rollbackrecord',
            name='status',
            field=models.IntegerField(choices=[(1, '回滚中'), (2, '回滚成功'), (3, '回滚失败')], default=1, verbose_name='状态'),
        ),
    ]
