# Generated by Django 2.2.1 on 2019-06-28 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20190628_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinedetails',
            name='details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web.Onlinelist'),
        ),
    ]
