# Generated by Django 2.2.1 on 2019-06-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20190628_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onlinedetails',
            old_name='details',
            new_name='details_id',
        ),
        migrations.RenameField(
            model_name='onlinedetails',
            old_name='staff',
            new_name='staff_id',
        ),
        migrations.AlterField(
            model_name='script',
            name='interpreter',
            field=models.CharField(choices=[('sh', 'bash'), ('py', 'python3')], default='py', max_length=16, verbose_name='解释器'),
        ),
    ]
