# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-21 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20190118_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploy',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.File', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='script',
            name='interpreter',
            field=models.CharField(choices=[('py', 'python3'), ('sh', 'bash')], default='py', max_length=16, verbose_name='解释器'),
        ),
    ]
