# Generated by Django 2.2.1 on 2019-07-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20190628_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlinedetails',
            name='details_id',
        ),
        migrations.AddField(
            model_name='onlinedetails',
            name='Online_project',
            field=models.CharField(blank=True, max_length=256, verbose_name='上线项目(版本号)'),
        ),
        migrations.AddField(
            model_name='onlinedetails',
            name='Online_time',
            field=models.DateTimeField(max_length=256, null=True, verbose_name='上线日期'),
        ),
        migrations.AddField(
            model_name='onlinedetails',
            name='Op_qz',
            field=models.CharField(max_length=256, null=True, verbose_name='运维签字'),
        ),
        migrations.AddField(
            model_name='onlinedetails',
            name='Pm_qz',
            field=models.CharField(max_length=256, null=True, verbose_name='产品签字'),
        ),
        migrations.AddField(
            model_name='onlinedetails',
            name='Rallback_result',
            field=models.CharField(max_length=256, null=True, verbose_name='回归结果测试产品签字'),
        ),
        migrations.AddField(
            model_name='onlinedetails',
            name='Rd_qz',
            field=models.CharField(max_length=256, null=True, verbose_name='rd签字'),
        ),
        migrations.AddField(
            model_name='onlinedetails',
            name='Rollback_name',
            field=models.CharField(max_length=128, null=True, verbose_name='回滚方案'),
        ),
        migrations.AddField(
            model_name='onlinedetails',
            name='Test_qz',
            field=models.CharField(max_length=256, null=True, verbose_name='测试签字'),
        ),
        migrations.AddField(
            model_name='onlinedetails',
            name='Ui_qz',
            field=models.CharField(max_length=256, null=True, verbose_name='ui签字'),
        ),
        migrations.AddField(
            model_name='onlinedetails',
            name='Zj_qz',
            field=models.CharField(max_length=256, null=True, verbose_name='总监签字'),
        ),
        migrations.AddField(
            model_name='onlinedetails',
            name='select_op',
            field=models.CharField(max_length=128, null=True, verbose_name='指定运维审核'),
        ),
        migrations.AddField(
            model_name='onlinedetails',
            name='select_project',
            field=models.CharField(max_length=128, null=True, verbose_name='选择项目负责人审核'),
        ),
        migrations.AddField(
            model_name='onlinedetails',
            name='select_test',
            field=models.CharField(max_length=128, null=True, verbose_name='指定测试审核'),
        ),
        migrations.AddField(
            model_name='onlinedetails',
            name='status',
            field=models.IntegerField(choices=[(1, '提交更新'), (2, '负责人审核通过'), (3, '预上线'), (4, '代码上线完成'), (5, '回归中'), (6, '回归完成'), (7, '回滚'), (8, '否决上线'), (9, '流程结束')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='onlinedetails',
            name='Online_step',
            field=models.TextField(null=True, verbose_name='上线步骤'),
        ),
        migrations.DeleteModel(
            name='Onlinelist',
        ),
    ]
