# Generated by Django 2.2.1 on 2019-07-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20190702_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onlinedetails',
            old_name='staff_id',
            new_name='staff',
        ),
        migrations.AlterField(
            model_name='onlinedetails',
            name='Op_qz',
            field=models.CharField(default='', max_length=256, null=True, verbose_name='运维签字'),
        ),
        migrations.AlterField(
            model_name='onlinedetails',
            name='Pm_qz',
            field=models.CharField(default='', max_length=256, null=True, verbose_name='产品签字'),
        ),
        migrations.AlterField(
            model_name='onlinedetails',
            name='Rallback_result',
            field=models.CharField(default='', max_length=256, null=True, verbose_name='回归结果测试产品签字'),
        ),
        migrations.AlterField(
            model_name='onlinedetails',
            name='Test_qz',
            field=models.CharField(default='', max_length=256, null=True, verbose_name='测试签字'),
        ),
        migrations.AlterField(
            model_name='onlinedetails',
            name='Ui_qz',
            field=models.CharField(default='', max_length=256, null=True, verbose_name='ui签字'),
        ),
        migrations.AlterField(
            model_name='onlinedetails',
            name='Zj_qz',
            field=models.CharField(default='', max_length=256, null=True, verbose_name='总监签字'),
        ),
        migrations.AlterField(
            model_name='onlinedetails',
            name='select_op',
            field=models.CharField(default='', max_length=128, null=True, verbose_name='指定运维审核'),
        ),
        migrations.AlterField(
            model_name='onlinedetails',
            name='select_project',
            field=models.CharField(default='', max_length=128, null=True, verbose_name='选择项目负责人审核'),
        ),
        migrations.AlterField(
            model_name='onlinedetails',
            name='select_test',
            field=models.CharField(default='', max_length=128, null=True, verbose_name='指定测试审核'),
        ),
        migrations.AlterField(
            model_name='script',
            name='interpreter',
            field=models.CharField(choices=[('py', 'python3'), ('sh', 'bash')], default='py', max_length=16, verbose_name='解释器'),
        ),
        migrations.AlterField(
            model_name='sqlcredential',
            name='Development_qz',
            field=models.CharField(default='', max_length=128, verbose_name='开发签字'),
        ),
        migrations.AlterField(
            model_name='sqlcredential',
            name='Project_confirm_qz',
            field=models.CharField(default='', max_length=128, verbose_name='项目负责人确认签字'),
        ),
        migrations.AlterField(
            model_name='sqlcredential',
            name='Project_qz',
            field=models.CharField(default='', max_length=128, verbose_name='项目负责人签字'),
        ),
        migrations.AlterField(
            model_name='sqlcredential',
            name='Rollback_name',
            field=models.CharField(default='', max_length=128, verbose_name='回滚方案'),
        ),
        migrations.AlterField(
            model_name='sqlcredential',
            name='Technical_qz',
            field=models.CharField(default='', max_length=128, verbose_name='技术总监签字'),
        ),
        migrations.AlterField(
            model_name='sqlcredential',
            name='op_qz',
            field=models.CharField(default='', max_length=256, verbose_name='运维签字'),
        ),
        migrations.AlterField(
            model_name='sqlcredential',
            name='select_op',
            field=models.CharField(default='', max_length=128, verbose_name='指定运维审核'),
        ),
        migrations.AlterField(
            model_name='sqlcredential',
            name='select_project',
            field=models.CharField(max_length=128, null=True, verbose_name='选择项目负责人审核'),
        ),
        migrations.AlterField(
            model_name='sqlcredential',
            name='select_test',
            field=models.CharField(default='', max_length=128, verbose_name='指定测试审核'),
        ),
    ]
