# Generated by Django 2.2.1 on 2019-07-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20190703_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sqlcredential',
            name='Project_confirm_qz',
        ),
        migrations.AddField(
            model_name='sqlcredential',
            name='pm_qz',
            field=models.CharField(default='', max_length=128, verbose_name='项目负责人（产品）确认签字'),
        ),
        migrations.AlterField(
            model_name='script',
            name='interpreter',
            field=models.CharField(choices=[('sh', 'bash'), ('py', 'python3')], default='py', max_length=16, verbose_name='解释器'),
        ),
    ]
