# Generated by Django 2.1.4 on 2019-04-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20190425_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlcredential',
            name='status',
            field=models.IntegerField(choices=[(1, '提交更新'), (2, '负责人审核'), (3, '回滚'), (8, '否决上线'), (9, '流程结束')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='script',
            name='interpreter',
            field=models.CharField(choices=[('py', 'python3'), ('sh', 'bash')], default='py', max_length=16, verbose_name='解释器'),
        ),
    ]
