# Generated by Django 2.1.4 on 2019-04-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20190429_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlinelist',
            name='test',
        ),
        migrations.AddField(
            model_name='onlinelist',
            name='Op_qz',
            field=models.CharField(max_length=256, null=True, verbose_name='运维签字'),
        ),
        migrations.AddField(
            model_name='onlinelist',
            name='Pm_qz',
            field=models.CharField(max_length=256, null=True, verbose_name='产品签字'),
        ),
        migrations.AddField(
            model_name='onlinelist',
            name='Test_qz',
            field=models.CharField(max_length=256, null=True, verbose_name='测试签字'),
        ),
        migrations.AddField(
            model_name='onlinelist',
            name='Ui_qz',
            field=models.CharField(max_length=256, null=True, verbose_name='ui签字'),
        ),
        migrations.AddField(
            model_name='onlinelist',
            name='Zj_qz',
            field=models.CharField(max_length=256, null=True, verbose_name='总监签字'),
        ),
        migrations.AlterField(
            model_name='script',
            name='interpreter',
            field=models.CharField(choices=[('sh', 'bash'), ('py', 'python3')], default='py', max_length=16, verbose_name='解释器'),
        ),
    ]
