# Generated by Django 2.1.4 on 2019-05-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20190429_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinelist',
            name='select_op',
            field=models.CharField(max_length=128, null=True, verbose_name='指定运维审核'),
        ),
        migrations.AddField(
            model_name='onlinelist',
            name='select_project',
            field=models.CharField(max_length=128, null=True, verbose_name='选择项目负责人审核'),
        ),
        migrations.AddField(
            model_name='onlinelist',
            name='select_test',
            field=models.CharField(max_length=128, null=True, verbose_name='指定测试审核'),
        ),
        migrations.AddField(
            model_name='sqlcredential',
            name='select_op',
            field=models.CharField(max_length=128, null=True, verbose_name='指定运维审核'),
        ),
        migrations.AddField(
            model_name='sqlcredential',
            name='select_project',
            field=models.CharField(max_length=128, null=True, verbose_name='选择项目负责人审核'),
        ),
        migrations.AddField(
            model_name='sqlcredential',
            name='select_test',
            field=models.CharField(max_length=128, null=True, verbose_name='指定测试审核'),
        ),
        migrations.AlterField(
            model_name='onlinelist',
            name='status',
            field=models.IntegerField(choices=[(1, '提交更新'), (2, '负责人审核通过'), (3, '预上线'), (4, '代码上线完成'), (5, '回归中'), (6, '回归完成'), (7, '回滚'), (8, '否决上线'), (9, '流程结束')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='sqlcredential',
            name='status',
            field=models.IntegerField(choices=[(1, '提交更新'), (2, '负责人审核通过'), (3, '运维上线完成'), (4, '否决上线'), (5, '回滚'), (6, '流程结束')], default=1, verbose_name='状态'),
        ),
    ]
