# Generated by Django 2.1.4 on 2019-05-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20190506_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinelist',
            name='Rd_qz',
            field=models.CharField(default=1, max_length=256, verbose_name='rd签字'),
            preserve_default=False,
        ),
    ]
