#!/bin/bash

project_name=$1
dir_time=$2
file_name=$3
# 所有代码存放目录
CODE_BASE_PATH="/home/yx/codes"
# 某个项目存放目录
PROJECT_PATH="$CODE_BASE_PATH/$project_name/$dir_time/${project_name}${dir_time}"
echo "$PROJECT_PATH"
# 项目所在目录
WEB_BASE_PATH="/home/yx/nginx/html"
# 更新文件的所在的目录
#UPDATE_FILE="/home/yx/file/$project_name/$dir_time"
# include文件所在目录
include_dir="/tmp"
if [ ! -f "/tmp/include.txt" ];then
  touch /tmp/include.txt
fi
echo "$UPDATE_FILE"
if [ -d $PROJECT_PATH ]
then
        # 拷贝文件到项目所在目录，但是要排除所有的配置文件意思是除了include，其余所有的都不同步
  rsync -av $PROJECT_PATH/ --include-from=$include_dir/include.txt --exclude=/*  $WEB_BASE_PATH
else
  unzip -d $PROJECT_PATH  $CODE_BASE_PATH/$project_name/$dir_time/$file_name
  rsync -av $PROJECT_PATH/ --include-from=$include_dir/include.txt --exclude=/*  $WEB_BASE_PATH
fi