#!/bin/bash
project_name=$1
dir_time=$2
file_name=$3
# 所有代码存放目录
CODE_BASE_PATH="/home/yx/codes"
# 某个项目代码存放目录
PROJECT_PATH="$CODE_BASE_PATH/$project_name/$dir_time/${project_name}${dir_time}/"
echo "$PROJECT_PATH"

# 项目所在目录
WEB_BASE_PATH="/home/yx/nginx/html/"
# include文件所在目录
include_dir="/tmp"
if [ ! -f "/tmp/exclude.list" ];then
  touch /tmp/exclude.list
fi
echo "$UPDATE_FILE"
if [ -d $PROJECT_PATH ]
then
        # 拷贝文件到项目所在目录，但是要排除所有的配置文件意思是除了include，其余所有的都不同步
  rsync -av $PROJECT_PATH --exclude-from "/tmp/exclude.list"   $WEB_BASE_PATH
else
  unzip -d $PROJECT_PATH  $CODE_BASE_PATH/$project_name/$dir_time/${file_name}  # 解压代码
  rsync -av $PROJECT_PATH --exclude-from "/tmp/exclude.list"  $WEB_BASE_PATH   # 拷贝文件到项目所在目录，但是要排除所有的配置文件
fi