# Generated by Django 2.2.1 on 2019-06-27 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('icon', models.CharField(max_length=32, verbose_name='图标')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=128, verbose_name='URL(含正则)')),
                ('title', models.CharField(max_length=32, verbose_name='权限名称')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='别名')),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Menu', verbose_name='管理菜单')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Permission', verbose_name='父菜单')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='名称')),
                ('permissions', models.ManyToManyField(to='rbac.Permission', verbose_name='关联权限')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('server_name', models.CharField(blank=True, max_length=32, verbose_name='SSH用户名')),
                ('server_private_key', models.TextField(blank=True, verbose_name='SSH私钥')),
                ('git_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='git用户名')),
                ('git_pwd', models.CharField(blank=True, max_length=32, null=True, verbose_name='git密码')),
                ('wechat_user', models.CharField(max_length=64, null=True, verbose_name='微信用户名')),
                ('email', models.EmailField(max_length=64, verbose_name='邮箱')),
                ('jobs', models.CharField(max_length=64, null=True, verbose_name='工作职位')),
                ('roles', models.ManyToManyField(to='rbac.Role', verbose_name='关联角色')),
            ],
        ),
    ]
